.\"Replace tpad with the program name, x with the Section Number
.TH tpad 1 "20 January 2013" "" "Linux User's Manual"

.SH NAME
tpad \- GTK based simple, fast, and easy to use text editor.

.SH SYNOPSIS
.B tpad
.RI [ FILE ]
.br

.SH DESCRIPTION
This manual page explains the \fBtpad\fP program. The \fBtpad\fP program is for editing text files, C, CPP, PHP, SVGs and more. 